Added -k to all lines of batch file generators so that we can keep track of out of date keys.
Changed a key in plancomparecontrol from merge_plan_file_format to compare_plan_file_format. This allows us to get rid of errors like;

	Error: Compare Plan File Token Fields don't Match