Still debugging the subareanetwork.
********************************************
|                                          |
|     Microsimulator - Version 4.0.46      |
|   Copyright (c) 2008 by AECOM Consult    |
|         Mon Sep 15 16:33:55 2008         |
|                                          |
********************************************


Reading Node File -- Record 266

Reading Link File -- Record 361

Reading Pocket Lane File -- Record 237

Reading Lane Connectivity File -- Record 1296

Reading Parking File -- Record 1006

Reading Activity Location File -- Record 1006

Reading Process Link File -- Record 2012

Reading Unsignalized Node File -- Record 271

Reading Timing Plan File -- Record 228

Reading Signal Coordinator File -- Record 83

Reading Signalized Node File -- Record 83

Reading Detector File -- Record 389

Reading Phasing Plan File -- Record 811

Reading Vehicle Type File -- Record 15

Reading Vehicle File -- Record 328961


Error: Next Phase 2 was Not Found at Node 2564

Mon Sep 15 16:33:56 2008 -- Process Terminated Due to Errors (0:00:01)

Press Enter to Continue